apiDebug: false
timeout: 20000
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    #blocUrl: 'http://0.0.0.0:8000'
    explorerUrl: 'http://tester9.centralus.cloudapp.azure.com:9000'
    stratoUrl: 'http://tester9.centralus.cloudapp.azure.com:80'
    blocUrl: 'http://tester9.centralus.cloudapp.azure.com:8000'
